services: 
  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/postgresql/data
  mongodb: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=achyutp10
      - MONGO_INITDB_ROOT_PASSWORD=achyutp10
    ports:
      - 27017:27017
    volumes: 
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: trycatchlearn/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=localhost:5432; User Id=postgres; Password=achyutp10; Database=auction
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: trycatchlearn/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=Server=mongodb://achyut10:achyut10@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
      - 7777:7777
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: trycatchlearn/identity-svc:latest
    build: 
      context: .
      dockerfile: src/ItentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=localhost:5432; User Id=postgres; Password=achyutp10; Database=identity
    ports:
      - 5001:80
    depends_on:
      - postgres